### ISSUE TITLE
Having a question about the multi LSTM code 

### ISSUE THREAD

**Issue by zhenlinliu** [amirstar/Deep-Forecast#1]
hello amirstar:
     I have a question about the code, why it is “for ind in range(len(preXTrain) - self.inputHorizon -1)” in the line 73 of the code, I think it should be “for ind in range(len(preXTrain) - 1)” , Could you tell me why, please.

**Comment by jacksonsshi** [comment]
I think  it is a bug

**Comment by amirstar** [comment]
Hello @zhenlinliu, @jacksonsshi,
The input for each LSTM must contain data from the last 12 time steps. Suppose len(preXTrain) = 100, then we can use preXTrain[88:] as an input to the LSTM and it would be our last sample. We can not feed the preXTrain[89:] into the LSTM.
